### ISSUE TITLE
Prepare Odin source for open publication

### ISSUE THREAD

**Issue by skymandr** [Odin-SMR/odin#6]
We want to move Odin to Github (some repositories are already in molflows github org). The Odin source code will he available in the org [Odin-SMR](https://github.com/Odin-SMR)

However, it may be the case that the source contains sensitive information.

- Look through source to make sure that no sensitive information is in the source tree
  - [x] qsmr
  - [x] qsmr-data
  - [x] hermod - see molflow/hermod#1
  - [x] odin-api - see #8 
  - [x] odincal - see molflow/odin-calibration#1
  - [x] odin_redo_documents
- Once finished, move repos to  [Odin-SMR](https://github.com/Odin-SMR)
